# Generated by Django 5.1.4 on 2024-12-31 14:47

import clickhouse_backend.models
import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="RequestLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    clickhouse_backend.models.DateTimeField(verbose_name="请求时间"),
                ),
                (
                    "api_path",
                    clickhouse_backend.models.StringField(verbose_name="接口地址"),
                ),
                (
                    "client_ip",
                    clickhouse_backend.models.StringField(
                        verbose_name="客户端 IP 地址"
                    ),
                ),
                (
                    "user_id",
                    clickhouse_backend.models.StringField(
                        default="", verbose_name="用户标识"
                    ),
                ),
                (
                    "user_agent",
                    clickhouse_backend.models.StringField(
                        verbose_name="User-Agent 信息"
                    ),
                ),
                (
                    "referer",
                    clickhouse_backend.models.StringField(
                        default="", verbose_name="Referer 来源"
                    ),
                ),
                (
                    "origin",
                    clickhouse_backend.models.StringField(
                        default="", verbose_name="Origin"
                    ),
                ),
                (
                    "status_code",
                    clickhouse_backend.models.UInt16Field(verbose_name="状态码"),
                ),
                (
                    "host",
                    clickhouse_backend.models.StringField(verbose_name="主机地址"),
                ),
                (
                    "duration",
                    clickhouse_backend.models.Float64Field(verbose_name="请求耗时"),
                ),
                (
                    "country",
                    clickhouse_backend.models.StringField(
                        default="", verbose_name="国家"
                    ),
                ),
                (
                    "region",
                    clickhouse_backend.models.StringField(
                        default="", verbose_name="区域"
                    ),
                ),
                (
                    "city",
                    clickhouse_backend.models.StringField(
                        default="", verbose_name="城市"
                    ),
                ),
                (
                    "time_zone",
                    clickhouse_backend.models.StringField(
                        default="", verbose_name="时区"
                    ),
                ),
                (
                    "device_brand",
                    clickhouse_backend.models.StringField(
                        default="", verbose_name="设备品牌"
                    ),
                ),
                (
                    "device_model",
                    clickhouse_backend.models.StringField(
                        default="", verbose_name="设备型号"
                    ),
                ),
                ("device_family", clickhouse_backend.models.StringField(default="")),
                (
                    "device_type",
                    clickhouse_backend.models.StringField(
                        default="", verbose_name="设备类型"
                    ),
                ),
                (
                    "os_family",
                    clickhouse_backend.models.StringField(
                        default="", verbose_name="操作系统名称"
                    ),
                ),
                (
                    "os_version",
                    clickhouse_backend.models.StringField(
                        default="", verbose_name="操作系统版本"
                    ),
                ),
                (
                    "browser_family",
                    clickhouse_backend.models.StringField(
                        default="", verbose_name="浏览器名称"
                    ),
                ),
                (
                    "browser_version",
                    clickhouse_backend.models.StringField(
                        default="", verbose_name="浏览器版本"
                    ),
                ),
                (
                    "accept_language",
                    clickhouse_backend.models.StringField(
                        default="", verbose_name="用户语言偏好"
                    ),
                ),
                (
                    "request_id",
                    clickhouse_backend.models.StringField(
                        default="", verbose_name="请求标识"
                    ),
                ),
                (
                    "query_params",
                    clickhouse_backend.models.StringField(
                        default="", verbose_name="query 参数"
                    ),
                ),
                (
                    "body_params",
                    clickhouse_backend.models.StringField(
                        default="", verbose_name="body 参数"
                    ),
                ),
                (
                    "method",
                    clickhouse_backend.models.StringField(
                        default="", verbose_name="请求方式, GET/POST/PUT/DELETE"
                    ),
                ),
                (
                    "tenant_id",
                    clickhouse_backend.models.StringField(
                        default="", verbose_name="租户 ID"
                    ),
                ),
            ],
            options={
                "verbose_name": "请求日志",
                "engine": clickhouse_backend.models.MergeTree(
                    order_by=("created_at",),
                    partition_by=clickhouse_backend.models.toYYYYMM("created_at"),
                ),
                "indexes": [
                    clickhouse_backend.models.Index(
                        fields=["api_path"],
                        granularity=64,
                        name="idx_api_path",
                        type=clickhouse_backend.models.BloomFilter(0.001),
                    ),
                    clickhouse_backend.models.Index(
                        fields=["user_id"],
                        granularity=64,
                        name="idx_user_id",
                        type=clickhouse_backend.models.BloomFilter(0.001),
                    ),
                    clickhouse_backend.models.Index(
                        fields=["request_id"],
                        granularity=64,
                        name="idx_request_id",
                        type=clickhouse_backend.models.BloomFilter(0.001),
                    ),
                ],
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("_overwrite_base_manager", django.db.models.manager.Manager()),
            ],
        ),
    ]
