# Generated by Django 5.1.4 on 2024-12-31 13:21

import clickhouse_backend.models
import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CeleryTaskResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "task_id",
                    clickhouse_backend.models.StringField(verbose_name="任务 ID"),
                ),
                (
                    "task_name",
                    clickhouse_backend.models.StringField(verbose_name="任务名称"),
                ),
                (
                    "status",
                    clickhouse_backend.models.StringField(verbose_name="任务状态"),
                ),
                (
                    "result",
                    clickhouse_backend.models.StringField(verbose_name="任务结果"),
                ),
                (
                    "traceback",
                    clickhouse_backend.models.StringField(
                        default="", verbose_name="异常信息"
                    ),
                ),
                ("created_at", clickhouse_backend.models.DateTimeField()),
            ],
            options={
                "verbose_name": "异步任务结果",
                "engine": clickhouse_backend.models.MergeTree(
                    order_by=("created_at",),
                    partition_by=clickhouse_backend.models.toYYYYMM("created_at"),
                ),
                "indexes": [
                    clickhouse_backend.models.Index(
                        fields=["task_name"],
                        granularity=64,
                        name="idx_task_name",
                        type=clickhouse_backend.models.BloomFilter(0.001),
                    ),
                    clickhouse_backend.models.Index(
                        fields=["status"],
                        granularity=64,
                        name="idx_status",
                        type=clickhouse_backend.models.BloomFilter(0.001),
                    ),
                ],
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("_overwrite_base_manager", django.db.models.manager.Manager()),
            ],
        ),
    ]
