# Generated by Django 5.1.4 on 2024-12-31 09:28

import common.db.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SystemUser",
            fields=[
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "id",
                    models.BigIntegerField(
                        default=common.db.models.generate_id,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_delete", models.BooleanField(default=False)),
                (
                    "username",
                    models.CharField(max_length=32, unique=True, verbose_name="用户名"),
                ),
                ("password", models.CharField(max_length=128, verbose_name="密码")),
                (
                    "nickname",
                    models.CharField(db_index=True, max_length=32, verbose_name="昵称"),
                ),
                (
                    "email",
                    models.CharField(max_length=64, unique=True, verbose_name="邮箱"),
                ),
                (
                    "mobile",
                    models.CharField(
                        max_length=32, unique=True, verbose_name="手机号码"
                    ),
                ),
                (
                    "avatar",
                    models.CharField(default="", max_length=128, verbose_name="头像"),
                ),
                (
                    "created_name",
                    models.CharField(max_length=32, verbose_name="创建人姓名"),
                ),
                (
                    "updated_name",
                    models.CharField(
                        default="", max_length=32, verbose_name="上次修改人姓名"
                    ),
                ),
                (
                    "last_login_at",
                    models.DateTimeField(null=True, verbose_name="上次登陆时间"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="是否激活"),
                ),
                (
                    "is_super",
                    models.BooleanField(default=False, verbose_name="是否是管理员"),
                ),
                (
                    "mfa_type",
                    models.PositiveSmallIntegerField(
                        choices=[(0, "未启用"), (1, "短信验证"), (2, "TOTP 验证")],
                        default=0,
                        verbose_name="MFA类型",
                    ),
                ),
                (
                    "totp_key",
                    models.CharField(
                        blank=True, max_length=32, null=True, verbose_name="TOTP 密钥"
                    ),
                ),
                (
                    "created",
                    common.db.models.ForeignKey(
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="admin_system_user_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建人",
                    ),
                ),
                (
                    "updated",
                    common.db.models.ForeignKey(
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="admin_system_user_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="上次修改人",
                    ),
                ),
            ],
            options={
                "verbose_name": "系统用户",
            },
        ),
    ]
