repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-ast
      - id: check-added-large-files
      - id: check-builtin-literals
      - id: check-docstring-first
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: debug-statements
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.8.4
    hooks:
      - id: ruff
        args:
          - --fix  # 启动自动修复
          - --select=E,F,W,I,B,C,Q  # 指定启用的检查规则
          - --ignore=E231  # 忽略某些规则
          - --line-length=120  # 设置最大行长度
      - id: ruff-format
  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.9
    hooks:
      - id: bandit
        name: bandit
        entry: bandit
        language: python
        types: [ python ]
  - repo: https://github.com/commitizen-tools/commitizen
    rev: v4.1.0
    hooks:
      - id: commitizen
