# Generated by Django 5.1.4 on 2025-01-01 04:55

import common.db.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Tenant",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        default=common.db.models.generate_id,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_delete", models.BooleanField(default=False)),
                (
                    "name",
                    models.CharField(
                        db_index=True, max_length=255, verbose_name="租户名称"
                    ),
                ),
                (
                    "contact_name",
                    models.CharField(max_length=64, verbose_name="联系人姓名"),
                ),
                (
                    "contact_email",
                    models.CharField(max_length=128, verbose_name="联系人邮箱"),
                ),
                (
                    "contact_mobile",
                    models.CharField(max_length=32, verbose_name="联系人电话"),
                ),
                (
                    "address",
                    models.TextField(
                        default="", max_length=255, verbose_name="租户地址"
                    ),
                ),
                (
                    "status",
                    models.PositiveSmallIntegerField(
                        choices=[(0, "激活"), (1, "未激活"), (2, "已暂停")],
                        verbose_name="租户状态",
                    ),
                ),
                (
                    "created_name",
                    models.CharField(max_length=32, verbose_name="创建人姓名"),
                ),
                (
                    "updated_name",
                    models.CharField(
                        default="", max_length=32, verbose_name="上次修改人姓名"
                    ),
                ),
                (
                    "created",
                    common.db.models.ForeignKey(
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tenant_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建人",
                    ),
                ),
                (
                    "updated",
                    common.db.models.ForeignKey(
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tenant_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="上次修改人",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="TenantUser",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        default=common.db.models.generate_id,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_delete", models.BooleanField(default=False)),
                (
                    "tenant_id",
                    models.BigIntegerField(db_index=True, verbose_name="租户 ID"),
                ),
                (
                    "username",
                    models.CharField(
                        db_index=True, max_length=64, verbose_name="用户名"
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="密码")),
                ("name", models.CharField(max_length=64, verbose_name="姓名")),
                (
                    "email",
                    models.CharField(
                        db_index=True, max_length=128, verbose_name="邮箱地址"
                    ),
                ),
                (
                    "mobile",
                    models.CharField(db_index=True, max_length=32, verbose_name="电话"),
                ),
                (
                    "is_super",
                    models.BooleanField(default=False, verbose_name="是否是租户管理员"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="是否激活"),
                ),
                (
                    "last_login_at",
                    models.DateTimeField(null=True, verbose_name="上次登陆时间"),
                ),
                (
                    "created_name",
                    models.CharField(max_length=32, verbose_name="创建人姓名"),
                ),
                (
                    "updated_name",
                    models.CharField(
                        default="", max_length=32, verbose_name="上次修改人姓名"
                    ),
                ),
                (
                    "created",
                    common.db.models.ForeignKey(
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tenant_user_created",
                        to="tenant.tenantuser",
                        verbose_name="创建人",
                    ),
                ),
                (
                    "updated",
                    common.db.models.ForeignKey(
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tenant_user_updated",
                        to="tenant.tenantuser",
                        verbose_name="上次修改人",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
